# Generated by Django 4.1.7 on 2023-02-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('credentials', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=50)),
                ('amount_of_source', models.CharField(max_length=50)),
                ('authorized_use', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PermitProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('credentials', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='000-000-0000', max_length=30)),
                ('alt_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('consulting_firm', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('state_abbrev', models.CharField(max_length=2)),
                ('permit_num', models.CharField(max_length=11)),
                ('docket_num', models.CharField(blank=True, max_length=9, null=True)),
                ('exp_date', models.DateField()),
                ('authorized_user', models.ManyToManyField(blank=True, related_name='permit', to='nhpp_api.authorizeduser')),
                ('inspection_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhpp_api.inspectionpriority')),
                ('material', models.ManyToManyField(blank=True, related_name='permit', to='nhpp_api.material')),
                ('permit_program', models.ManyToManyField(blank=True, related_name='permit', to='nhpp_api.permitprogram')),
                ('primary_rso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_rso', to='nhpp_api.rso')),
                ('program_codes', models.ManyToManyField(to='nhpp_api.programcode')),
            ],
        ),
    ]
