# Generated by Django 4.1.7 on 2023-02-20 14:27

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuMaterialsUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('credentials', models.CharField(blank=True, max_length=50, null=True)),
                ('material_and_use', multiselectfield.db.fields.MultiSelectField(choices=[('100', '10 CFR 35.100'), ('200', '10 CFR 35.200'), ('300', '10 CFR 35.300'), ('500', '10 CFR 35.500'), ('200 exception', '10 CFR 35.200 (except generators)')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('ANY', 'Any'), ('SEALED SOURCES', 'Sealed Sources')], default='ANY', max_length=20)),
                ('amount_of_source', models.CharField(max_length=100)),
                ('authorized_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhpp_api.authorizeduse')),
            ],
        ),
        migrations.CreateModel(
            name='PermitProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('credentials', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='000-000-0000', max_length=30)),
                ('alt_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('consulting_firm', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('state_abbrev', models.CharField(max_length=2)),
                ('permit_num', models.CharField(max_length=11)),
                ('docket_num', models.CharField(blank=True, max_length=9, null=True)),
                ('exp_date', models.DateField()),
                ('program_codes', multiselectfield.db.fields.MultiSelectField(choices=[(2110, 2110), (2120, 2120), (2121, 2121), (3610, 3610), (3620, 3620), (2240, 2240)], max_length=20)),
                ('inspection_priority', models.IntegerField(choices=[(2, 2), (3, 3), (5, 5)], default='3')),
                ('alt_rso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_alt_rso', to='nhpp_api.rso')),
                ('authorized_user', models.ManyToManyField(blank=True, to='nhpp_api.authorizeduser')),
                ('material', models.ManyToManyField(blank=True, to='nhpp_api.material')),
                ('permit_program', models.ManyToManyField(blank=True, to='nhpp_api.permitprogram')),
                ('primary_rso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_rso', to='nhpp_api.rso')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhpp_api.source'),
        ),
    ]
