# Generated by Django 4.1.7 on 2023-02-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhpp_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='authorized_use',
        ),
        migrations.AddField(
            model_name='permit',
            name='material',
            field=models.ManyToManyField(to='nhpp_api.material'),
        ),
    ]
