# Generated by Django 4.1.7 on 2023-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhpp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcode',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
