# Generated by Django 4.1.7 on 2023-02-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhpp_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuMaterialsUse',
        ),
    ]
