# Generated by Django 4.1.7 on 2023-02-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhpp_api', '0002_alter_programcode_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='amount_of_source',
            field=models.CharField(max_length=255),
        ),
    ]
