# Generated by Django 4.1.7 on 2023-02-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhpp_api', '0003_alter_material_amount_of_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='authorized_use',
        ),
    ]
