# Generated by Django 4.1.7 on 2023-02-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhpp_api', '0004_remove_material_authorized_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='permit',
            name='authorized_use',
            field=models.ManyToManyField(blank=True, to='nhpp_api.authorizeduse'),
        ),
    ]
