# Generated by Django 4.1.7 on 2023-02-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhpp_api', '0005_authorizeduse_permit_authorized_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcode',
            name='description',
        ),
    ]
